# Generated by Django 5.2.1 on 2025-06-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.docteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.patient')),
            ],
        ),
    ]
