# Generated by Django 5.2.1 on 2025-06-16 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0001_initial'),
        ('utilisateurs', '0003_user_code_expires_at_user_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['date', 'heure'], 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='docteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='utilisateurs.docteur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='lieu',
            field=models.CharField(max_length=255, verbose_name='Lieu du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='utilisateurs.patient'),
        ),
    ]
