# Generated by Django 5.2.1 on 2025-06-16 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_alter_rendezvous_options_alter_rendezvous_docteur_and_more'),
        ('utilisateurs', '0003_user_code_expires_at_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='utilisateurs.docteur')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('docteur', 'jour', 'heure_debut')},
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.creneauhoraire'),
        ),
    ]
