# Generated by Django 5.2.1 on 2025-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor_request',
            field=models.BooleanField(default=False),
        ),
    ]
