# Generated by Django 5.2.1 on 2025-06-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_docteur_bio_docteur_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docteur_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
