# Generated by Django 5.2.1 on 2025-06-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_docteur_user'),
    ]

    operations = [
    ]
