# Generated by Django 5.2.1 on 2025-06-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_user_adresse_user_date_naiss_user_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['nom'], 'verbose_name': 'Specialite', 'verbose_name_plural': 'Specialites'},
        ),
        migrations.AddField(
            model_name='patient',
            name='docteur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='utilisateurs.docteur'),
        ),
    ]
